// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/summarize": {
            "post": {
                "description": "Generate an AI summary of the article content. Returns cached result if available, otherwise streams the response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Generate AI summary",
                "parameters": [
                    {
                        "description": "Summarize request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.summarizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cached summary",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.summarizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/ai/translate": {
            "post": {
                "description": "Translate article content. Returns cached result if available, otherwise streams block translations via SSE.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Generate AI translation",
                "parameters": [
                    {
                        "description": "Translate request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.translateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.translateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/ai/translate/batch": {
            "post": {
                "description": "Translate multiple articles' titles and summaries. Returns NDJSON stream.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-ndjson"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Batch translate articles",
                "parameters": [
                    {
                        "description": "Batch translate request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.batchTranslateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gist_backend_internal_service.BatchTranslateResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/proxy/image/{encoded}": {
            "get": {
                "description": "Proxies external images to avoid triggering anti-crawling mechanisms",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "Proxy external image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64 URL-safe encoded image URL",
                        "name": "encoded",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/entries": {
            "get": {
                "description": "Get a list of entries with optional filters and pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "List entries",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by feed ID",
                        "name": "feedId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by folder ID",
                        "name": "folderId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by content type (article, picture, notification)",
                        "name": "contentType",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only return unread entries",
                        "name": "unreadOnly",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only return starred entries",
                        "name": "starredOnly",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of entries (default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.entryListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/entries/mark-read": {
            "post": {
                "description": "Mark all entries as read, optionally filtered by feed or folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Mark all as read",
                "parameters": [
                    {
                        "description": "Filter criteria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.markAllReadRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/entries/{id}": {
            "get": {
                "description": "Get a single entry by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Get entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.entryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/entries/{id}/fetch-readable": {
            "post": {
                "description": "Extract readable content from the entry's original URL using readability",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Fetch readable content",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.readableContentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/entries/{id}/read": {
            "patch": {
                "description": "Mark an entry as read or unread",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Update read status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Read status",
                        "name": "read",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateReadRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/entries/{id}/starred": {
            "patch": {
                "description": "Mark an entry as starred or unstarred",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Update starred status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Starred status",
                        "name": "starred",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateStarredRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/feeds": {
            "get": {
                "description": "Get a list of all subscribed feeds",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeds"
                ],
                "summary": "List feeds",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by folder ID",
                        "name": "folderId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handler.feedResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Subscribe to a new RSS/Atom feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeds"
                ],
                "summary": "Create a feed",
                "parameters": [
                    {
                        "description": "Feed creation request",
                        "name": "feed",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createFeedRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "Created"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Unsubscribe from multiple feeds at once",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "feeds"
                ],
                "summary": "Delete multiple feeds",
                "parameters": [
                    {
                        "description": "Feed IDs to delete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.deleteFeedsRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/feeds/preview": {
            "get": {
                "description": "Fetch information about a feed from its URL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeds"
                ],
                "summary": "Preview a feed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feed URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.feedPreviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/feeds/refresh": {
            "post": {
                "description": "Trigger an immediate refresh of all subscribed feeds",
                "tags": [
                    "feeds"
                ],
                "summary": "Refresh all feeds",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "409": {
                        "description": "Refresh already in progress",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/feeds/{id}": {
            "put": {
                "description": "Update the title or folder of an existing feed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeds"
                ],
                "summary": "Update a feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Feed ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Feed update request",
                        "name": "feed",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateFeedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.feedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Unsubscribe from a feed",
                "tags": [
                    "feeds"
                ],
                "summary": "Delete a feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Feed ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/feeds/{id}/type": {
            "patch": {
                "description": "Change the content type of a feed (article/picture/notification)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "feeds"
                ],
                "summary": "Update feed type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Feed ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Type update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/folders": {
            "get": {
                "description": "Get a list of all folders",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "List folders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handler.folderResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new folder to organize feeds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Create a folder",
                "parameters": [
                    {
                        "description": "Folder creation request",
                        "name": "folder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.folderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "Created"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete multiple folders at once (also deletes feeds in them)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Delete multiple folders",
                "parameters": [
                    {
                        "description": "Folder IDs to delete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.deleteFoldersRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/folders/{id}": {
            "put": {
                "description": "Update the name or parent ID of an existing folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Update a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Folder update request",
                        "name": "folder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.folderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.folderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing folder",
                "tags": [
                    "folders"
                ],
                "summary": "Delete a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/folders/{id}/type": {
            "patch": {
                "description": "Change the content type of a folder (article/picture/notification)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Update folder type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Type update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateFolderTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/opml/export": {
            "get": {
                "description": "Export all feeds and folders to an OPML file",
                "produces": [
                    "text/xml"
                ],
                "tags": [
                    "opml"
                ],
                "summary": "Export OPML",
                "responses": {
                    "200": {
                        "description": "OPML file content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/opml/import": {
            "post": {
                "description": "Start importing feeds and folders from an OPML file",
                "consumes": [
                    "multipart/form-data",
                    "text/xml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "opml"
                ],
                "summary": "Import OPML",
                "parameters": [
                    {
                        "type": "file",
                        "description": "OPML file to import",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.importStartedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel the current import task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "opml"
                ],
                "summary": "Cancel Import",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.importCancelledResponse"
                        }
                    }
                }
            }
        },
        "/opml/import/status": {
            "get": {
                "description": "Get current import task status via SSE stream",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "opml"
                ],
                "summary": "Import Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gist_backend_internal_service.ImportTask"
                        }
                    }
                }
            }
        },
        "/settings/ai": {
            "get": {
                "description": "Get the AI provider configuration with masked API keys",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get AI settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.aiSettingsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the AI provider configuration. Empty apiKey keeps existing key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Update AI settings",
                "parameters": [
                    {
                        "description": "AI settings",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.aiSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.aiSettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/settings/ai/test": {
            "post": {
                "description": "Test the AI provider connection with a \"Hello world\" message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Test AI connection",
                "parameters": [
                    {
                        "description": "AI test configuration",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.aiTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.aiTestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/starred-count": {
            "get": {
                "description": "Get the total count of starred entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Get starred count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.starredCountResponse"
                        }
                    }
                }
            }
        },
        "/unread-counts": {
            "get": {
                "description": "Get a map of feed IDs to their respective unread entry counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entries"
                ],
                "summary": "Get unread counts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.unreadCountsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gist_backend_internal_service.BatchTranslateResult": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "gist_backend_internal_service.ImportResult": {
            "type": "object",
            "properties": {
                "feedsCreated": {
                    "type": "integer"
                },
                "feedsSkipped": {
                    "type": "integer"
                },
                "foldersCreated": {
                    "type": "integer"
                },
                "foldersSkipped": {
                    "type": "integer"
                }
            }
        },
        "gist_backend_internal_service.ImportTask": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "current": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "feed": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/gist_backend_internal_service.ImportResult"
                },
                "status": {
                    "description": "\"running\", \"done\", \"error\", \"cancelled\"",
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.aiSettingsRequest": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "autoSummary": {
                    "type": "boolean"
                },
                "autoTranslate": {
                    "type": "boolean"
                },
                "baseUrl": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "rateLimit": {
                    "type": "integer"
                },
                "reasoningEffort": {
                    "type": "string"
                },
                "summaryLanguage": {
                    "type": "string"
                },
                "thinking": {
                    "type": "boolean"
                },
                "thinkingBudget": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.aiSettingsResponse": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "autoSummary": {
                    "type": "boolean"
                },
                "autoTranslate": {
                    "type": "boolean"
                },
                "baseUrl": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "rateLimit": {
                    "type": "integer"
                },
                "reasoningEffort": {
                    "type": "string"
                },
                "summaryLanguage": {
                    "type": "string"
                },
                "thinking": {
                    "type": "boolean"
                },
                "thinkingBudget": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.aiTestRequest": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "baseUrl": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "reasoningEffort": {
                    "type": "string"
                },
                "thinking": {
                    "type": "boolean"
                },
                "thinkingBudget": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.aiTestResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.batchTranslateRequest": {
            "type": "object",
            "properties": {
                "articles": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "summary": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "internal_handler.createFeedRequest": {
            "type": "object",
            "properties": {
                "folderId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_handler.deleteFeedsRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.deleteFoldersRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.entryListResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler.entryResponse"
                    }
                },
                "hasMore": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.entryResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "feedId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "readableContent": {
                    "type": "string"
                },
                "starred": {
                    "type": "boolean"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_handler.feedPreviewResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "itemCount": {
                    "type": "integer"
                },
                "lastUpdated": {
                    "type": "string"
                },
                "siteUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_handler.feedResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "etag": {
                    "type": "string"
                },
                "folderId": {
                    "type": "string"
                },
                "iconPath": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastModified": {
                    "type": "string"
                },
                "siteUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_handler.folderRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_handler.folderResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_handler.importCancelledResponse": {
            "type": "object",
            "properties": {
                "cancelled": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.importStartedResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_handler.markAllReadRequest": {
            "type": "object",
            "properties": {
                "feedId": {
                    "type": "string"
                },
                "folderId": {
                    "type": "string"
                }
            }
        },
        "internal_handler.readableContentResponse": {
            "type": "object",
            "properties": {
                "readableContent": {
                    "type": "string"
                }
            }
        },
        "internal_handler.starredCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.summarizeRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "entryId": {
                    "type": "string"
                },
                "isReadability": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler.summarizeResponse": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "internal_handler.translateRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "entryId": {
                    "type": "string"
                },
                "isReadability": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler.translateResponse": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "internal_handler.unreadCountsResponse": {
            "type": "object",
            "properties": {
                "counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_handler.updateFeedRequest": {
            "type": "object",
            "properties": {
                "folderId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateFolderTypeRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateReadRequest": {
            "type": "object",
            "properties": {
                "read": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.updateStarredRequest": {
            "type": "object",
            "properties": {
                "starred": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.updateTypeRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Gist API",
	Description:      "This is a modern RSS reader API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
